 --Inserir novo colaborador

INSERT INTO brh.papel (id, nome)
VALUES
(8, 'Especialista de Negócios');

INSERT INTO brh.endereco (cep, uf, cidade, bairro)
VALUES
('05452-060', 'SP', 'São Paulo', 'Vila Madalena')

INSERT INTO brh.colaborador (matricula, nome, cpf, salario, departamento, cep, logradouro, complemento_endereco)
VALUES
('A124', 'Fulano de Tal', '259.669.570-70', '6476', 'SEDES', '05452-060', 'Rua Putumuju', 'casa 33');

INSERT INTO brh.telefone_colaborador (colaborador, numero, tipo)
VALUES
('A124', '(61) 99999-9999', 'M');

INSERT INTO brh.telefone_colaborador (colaborador, numero, tipo)
VALUES
('A124', '(61) 3030-4040', 'R');

INSERT INTO brh.email_colaborador (colaborador, email, tipo)
VALUES
('A124', 'fulano@email.com', 'P');

INSERT INTO brh.email_colaborador (colaborador, email, tipo)
VALUES
('A124', 'fulano.tal@brh.com', 'T');

INSERT INTO brh.projeto (id, nome, responsavel, inicio, fim)
VALUES
(5, 'BI', 'K123', to_date('2020-03-25', 'yyyy-mm-dd'), null);

INSERT INTO brh.dependente (cpf, colaborador, nome, parentesco, data_nascimento)
VALUES
('114.535.188-27', 'A124', 'Cicrana de Tal', 'CÃ´njuge', to_date('1968-11-22', 'yyyy-mm-dd'));

INSERT INTO brh.dependente (cpf, colaborador, nome, parentesco, data_nascimento)
VALUES
('741.301.168-94', 'A124', 'Beltrana de Tal', 'Filho(a)', to_date('2008-04-15', 'yyyy-mm-dd'));

INSERT INTO brh.atribuicao (projeto, colaborador, papel)
VALUES
(5, 'A124', 8);

 --Relatório de cônjuges
 
 SELECT * FROM BRH.DEPENDENTE WHERE PARENTESCO = 'CÃ´njuge'
 
 -- SELECT * FROM BRH.DEPENDENTE WHERE PARENTESCO = 'CÃ´njuge'
 
 -- Filtrar dependentes
 
SELECT * FROM BRH.DEPENDENTE WHERE NOME LIKE 'H%' AND TO_CHAR(DATA_NASCIMENTO, 'MM') >= 4 AND TO_CHAR(DATA_NASCIMENTO, 'MM')<= 6;

 -- Consulta de sálarios
 
SELECT BRH.COLABORADOR.NOME, MAX(BRH.COLABORADOR.SALARIO) AS MAIOR_SALARIO FROM BRH.COLABORADOR GROUP BY BRH.COLABORADOR.NOME ORDER BY MAIOR_SALARIO DESC;

 --Relatório de Senioridade
 
create table brh.senioridade (
    salario nvarchar2(50) not null,
    senioridade varchar2(50) not null,
	constraint pk_senioridade primary key (senioridade)
    );
    
 --carga de dados senioridade
INSERT INTO brh.senioridade (senioridade, salario)
VALUES
('Junior', 'até 3000,00');

INSERT INTO brh.senioridade (senioridade, salario)
VALUES
('Pleno', 'De 3000,01 a 6000,00');

INSERT INTO brh.senioridade (senioridade, salario)
VALUES
('Senior', 'De 6000,01 a 20000,00');

INSERT INTO brh.senioridade (senioridade, salario)
VALUES
('Corpo diretor', 'Acima de 20000,00');


SELECT * FROM BRH.COLABORADOR WHERE SALARIO <= '3000'

SELECT * FROM BRH.COLABORADOR WHERE SALARIO >= '3000,01' AND SALARIO <= '6000'

SELECT * FROM BRH.COLABORADOR WHERE SALARIO >= '6000,01' AND SALARIO <= '20000'

SELECT * FROM BRH.COLABORADOR WHERE SALARIO >= '20000,01'

UPDATE BRH.COLABORADOR SET SENIORIDADE = 'CORPO DIRETOR' WHERE MATRICULA = 'A123';
UPDATE BRH.COLABORADOR SET SENIORIDADE = 'JUNIOR' WHERE MATRICULA = 'B123';
UPDATE BRH.COLABORADOR SET SENIORIDADE = 'SENIOR' WHERE MATRICULA = 'C123';
UPDATE BRH.COLABORADOR SET SENIORIDADE = 'JUNIOR' WHERE MATRICULA = 'D123';
UPDATE BRH.COLABORADOR SET SENIORIDADE = 'SENIOR' WHERE MATRICULA = 'E123';
UPDATE BRH.COLABORADOR SET SENIORIDADE = 'SENIOR' WHERE MATRICULA = 'F123';
UPDATE BRH.COLABORADOR SET SENIORIDADE = 'SENIOR' WHERE MATRICULA = 'G123';
UPDATE BRH.COLABORADOR SET SENIORIDADE = 'SENIOR' WHERE MATRICULA = 'H123';
UPDATE BRH.COLABORADOR SET SENIORIDADE = 'SENIOR' WHERE MATRICULA = 'I123';
UPDATE BRH.COLABORADOR SET SENIORIDADE = 'JUNIOR' WHERE MATRICULA = 'J123';
UPDATE BRH.COLABORADOR SET SENIORIDADE = 'SENIOR' WHERE MATRICULA = 'K123';
UPDATE BRH.COLABORADOR SET SENIORIDADE = 'SENIOR' WHERE MATRICULA = 'L123';
UPDATE BRH.COLABORADOR SET SENIORIDADE = 'SENIOR' WHERE MATRICULA = 'M123';
UPDATE BRH.COLABORADOR SET SENIORIDADE = 'PLENO' WHERE MATRICULA = 'N123';
UPDATE BRH.COLABORADOR SET SENIORIDADE = 'SENIOR' WHERE MATRICULA = 'O123';
UPDATE BRH.COLABORADOR SET SENIORIDADE = 'SENIOR' WHERE MATRICULA = 'P123';
UPDATE BRH.COLABORADOR SET SENIORIDADE = 'JUNIOR' WHERE MATRICULA = 'Q123';
UPDATE BRH.COLABORADOR SET SENIORIDADE = 'SENIOR' WHERE MATRICULA = 'R123';
UPDATE BRH.COLABORADOR SET SENIORIDADE = 'JUNIOR' WHERE MATRICULA = 'S123';
UPDATE BRH.COLABORADOR SET SENIORIDADE = 'SENIOR' WHERE MATRICULA = 'T123';
UPDATE BRH.COLABORADOR SET SENIORIDADE = 'CORPO DIRETOR' WHERE MATRICULA = 'U123';
UPDATE BRH.COLABORADOR SET SENIORIDADE = 'PLENO' WHERE MATRICULA = 'V123';
UPDATE BRH.COLABORADOR SET SENIORIDADE = 'PLENO' WHERE MATRICULA = 'W123';
UPDATE BRH.COLABORADOR SET SENIORIDADE = 'SENIOR' WHERE MATRICULA = 'X123';
UPDATE BRH.COLABORADOR SET SENIORIDADE = 'PLENO' WHERE MATRICULA = 'Y123';
UPDATE BRH.COLABORADOR SET SENIORIDADE = 'CORPO DIRETOR' WHERE MATRICULA = 'Z123';
UPDATE BRH.COLABORADOR SET SENIORIDADE = 'PLENO' WHERE MATRICULA = 'A124';

SELECT MATRICULA, NOME, SALARIO, SENIORIDADE FROM BRH.COLABORADOR;

 --Relatório de contatos
 
SELECT 
    BRH.COLABORADOR.NOME,
    BRH.TELEFONE_COLABORADOR.NUMERO,
    BRH.EMAIL_COLABORADOR.EMAIL
FROM
    BRH.TELEFONE_COLABORADOR
        JOIN BRH.COLABORADOR ON BRH.TELEFONE_COLABORADOR.COLABORADOR = BRH.COLABORADOR.MATRICULA
        JOIN BRH.EMAIL_COLABORADOR ON BRH.EMAIL_COLABORADOR.COLABORADOR = BRH.COLABORADOR.MATRICULA
WHERE
        brh.email_colaborador.tipo = 'T'
    AND brh.telefone_colaborador.tipo = 'M' OR brh.telefone_colaborador.tipo = 'C'
ORDER BY
( brh.colaborador.nome );

commit

